nuget:
    account_feed:true
    project_feed:true

build_script:
    - dotnet publish -c Release -r win10-x64
    - dotnet publish -c Release -r win10-x86
    - dotnet publish -c Release -r ubuntu.16.10-x64

build: off